label: Liste
description: 'La <em>liste</em> affiche des aperçus des types de contenu sélectionnés – sous forme de vue d’ensemble filtrable ou limitée à certains thèmes – triés par date, titre ou pondération.'
